
/* XI: EXTERN INTERRUPT */

/* DI: DIGITALE INPUT */

/* DO: DIGITALE OUTPUT */
#define MP_DC_DC_EN                                        MCUPIN(DO_DC_DC_EN_GPIO_Port, DO_DC_DC_EN_Pin)
#define MP_LED_GREEN                                       MCUPIN(DO_LED_GREEN_GPIO_Port, DO_LED_GREEN_Pin)
#define MP_MEM_PWR_EN                                      MCUPIN(DO_MEM_PWR_EN_GPIO_Port, DO_MEM_PWR_EN_Pin)
#define MP_SPI_DFLASH_CS                                   MCUPIN(DO_SPI_DFLASH_CS_GPIO_Port, DO_SPI_DFLASH_CS_Pin)

/* OO: DIGITALE OPEN DRAIN OUTPUT */
